apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::870258692307:role/eksctl-roboshop-nodegroup-spot-NodeInstanceRole-Pzykh6pl33bw
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::870258692307:user/anand
      username: anand
    - groups:
      - roboshop-admin
      userarn: arn:aws:iam::870258692307:user/sneha
      username: sneha  
    
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::870258692307:user/subbu
      username: subbu
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::870258692307:user/rama
      username: rama       
kind: ConfigMap
metadata:
  creationTimestamp: "2026-04-19T08:56:23Z"
  name: aws-auth
  namespace: kube-system
  
  uid: b4622ef9-baf9-41ee-b585-5ea71cf8f91e


